### ISSUE TITLE
Pull Request to paulcunnane's master branch and docu rework

### ISSUE THREAD

**Issue by StephanStS** [eschava/node-red-contrib-edge-trigger#1]
Hello @eschava, 
I would propose to do some minor beautification of the documentation. 
Your branch is ahead of paulcunnnane's upstream/master, do you plan to do a pull request? Depending on this I would use your branche for the "docu investigation" :-)
Regards
StephanStS

**Comment by eschava** [comment]
I've adopted this node from Paul so there is no need to do a pull request to the original branch

**Comment by StephanStS** [comment]
@eschava: Awaiting your review of my [actual docu rework status](https://github.com/StephanStS/node-red-contrib-edge-trigger/blob/master/README.md). 
If this is fine for you I will issue a pull request.

**Comment by eschava** [comment]
Thank you again for your work!
Released as 0.2.0
