### ISSUE TITLE
Hysteresis node: Edge property is not set

### ISSUE THREAD

**Issue by StephanStS** [eschava/node-red-contrib-edge-trigger#2]
The description of the `hysteresis` node says:
*The outgoing message has its edge property set to rising or falling.*

All three node output only the unmodified incoming message. No property `msg.edge` is set.
Output of the hysteresis node: 
![grafik](https://user-images.githubusercontent.com/57687516/83678809-9b986500-a5de-11ea-908d-c1ffafdacc34.png)

**Comment by eschava** [comment]
Could you please share your flow?

**Comment by StephanStS** [comment]
You could use the second example [there](https://github.com/StephanStS/node-red-contrib-edge-trigger#example-of-the-hysteresis-node) (you need to activate the debug panel output).

**Comment by StephanStS** [comment]
Sorry, that was my fault. I only looked at the msg.payload and not at the complete msg object.  
![grafik](https://user-images.githubusercontent.com/57687516/83740611-5c5a2a80-a657-11ea-9f3a-2fdf8f51e7bd.png)

I've added this in the [example 2](https://github.com/StephanStS/node-red-contrib-edge-trigger/blob/master/README.md#hysteresis_example2) of my docu rework proposal.
