### ISSUE TITLE
NPM package includes 27MB of cache files

### ISSUE THREAD

**Issue by mgjbroadbent** [eschava/node-red-contrib-edge-trigger#8]
The node-red-contrib-edge-trigger v1.0.0 package on npmjs is 35MB in size.  In the package there is 27MB of files in a `.cache` directory.  I suspect these are not required.

```
8	./node-red-contrib-edge-trigger/dist
1	./node-red-contrib-edge-trigger/edge-trigger
1	./node-red-contrib-edge-trigger/examples
1	./node-red-contrib-edge-trigger/assets
27	./node-red-contrib-edge-trigger/.cache
1	./node-red-contrib-edge-trigger/.idea
35	./node-red-contrib-edge-trigger
35	.
```

Could these be removed to reduce the size of the package?

Many thanks
Mark

**Comment by eschava** [comment]
Wow, thanks for that observation! Fixed
